spring:
  application:
    name: security
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      password: 123456
      username: root
    url: jdbc:log4jdbc:mysql://118.89.113.147:3310/zdxhxgk?characterEncoding=UTF8&autoReconnect=true
mybatis-plus:
mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 9001
  servlet:
    context-path: /security
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

